apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: my-s3-bucket
spec:
  forProvider:
    locationConstraint: us-west-2
    acl: private
  providerConfigRef:
    name: aws-provider
