apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-provider
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::420373265166:role/crossplane-role
spec:
  args:
    - --debug
  podSecurityContext:
    fsGroup: 2000 # This is needed for IRSA (IAM Roles for Service Accounts)

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: aws-provider
spec:
  package: xpkg.upbound.io/upbound/provider-aws:v0.40.0
  controllerConfigRef:
    name: aws-provider